# Generated by Django 3.1.7 on 2021-03-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20210310_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('lesson_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('lesson_name', models.CharField(max_length=200)),
                ('lesson_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lesson_description', models.TextField()),
                ('lesson_type', models.CharField(choices=[('lesson', 'Lesson'), ('block', 'Block'), ('intensive', 'Intensive')], max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Lessons',
            },
        ),
        migrations.DeleteModel(
            name='Blocks',
        ),
        migrations.DeleteModel(
            name='Intensive',
        ),
        migrations.DeleteModel(
            name='Lessons',
        ),
    ]
